# Generated by Django 5.1.4 on 2026-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dropdownlist_formdefinition_remove_task_kpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageauthorization',
            name='access_password',
            field=models.CharField(blank=True, help_text='Single password for all projects/packages under this VVB authorization', max_length=128),
        ),
    ]
