# Generated by Django 6.0.6 on 2026-07-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_packageauthorization_access_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedLibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_library', to='core.packageauthorization')),
                ('library_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core.librarydocument')),
            ],
            options={
                'unique_together': {('authorization', 'library_document')},
            },
        ),
    ]
