# Generated by Django 6.0.6 on 2026-07-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_formdefinition_created_by_remove_seeded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdefinition',
            options={'ordering': ['order', 'code'], 'verbose_name': 'Form Detail', 'verbose_name_plural': 'Form Details'},
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Form Number'),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='form_type',
            field=models.CharField(choices=[('project', 'Project'), ('master_record', 'Master Record'), ('proposal', 'Proposal')], default='project', max_length=20, verbose_name='Form Type'),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Form Name'),
        ),
    ]
