# Generated by Django 5.1.4 on 2026-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_formdefinition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinition',
            name='form_type',
            field=models.CharField(choices=[('project', 'Project'), ('master_record', 'Master Record'), ('proposal', 'Proposal'), ('others', 'Others')], default='project', max_length=20, verbose_name='Form Type'),
        ),
    ]
