# Generated by Django 5.1.4 on 2026-07-09 11:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_teammember_designation_teammember_position_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTableLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('column_headers', models.JSONField(default=list, help_text='Ordered list of column heading labels.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_table_layouts', to=settings.AUTH_USER_MODEL)),
                ('form_definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_layout', to='core.formdefinition')),
            ],
            options={
                'verbose_name': 'Form Table Layout',
                'verbose_name_plural': 'Form Table Layouts',
            },
        ),
    ]
