# Generated by Django 5.1.4 on 2026-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_formtablelayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('verifier_1', 'Verifier 1'), ('verifier_2', 'Verifier 2'), ('verifier_3', 'Verifier 3'), ('verifier_in_training', 'Verifier In-Training'), ('lead_verifier', 'Lead Verifier'), ('co_lead_verifier', 'Co-Lead Verifier'), ('technical_expert_1', 'Technical Expert 1'), ('technical_expert_2', 'Technical Expert 2'), ('peer_reviewer', 'Peer Reviewer')], max_length=30, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user_role',
            field=models.CharField(blank=True, choices=[('verifier_1', 'Verifier 1'), ('verifier_2', 'Verifier 2'), ('verifier_3', 'Verifier 3'), ('verifier_in_training', 'Verifier In-Training'), ('lead_verifier', 'Lead Verifier'), ('co_lead_verifier', 'Co-Lead Verifier'), ('technical_expert_1', 'Technical Expert 1'), ('technical_expert_2', 'Technical Expert 2'), ('peer_reviewer', 'Peer Reviewer')], max_length=30, verbose_name='User Role'),
        ),
    ]
