# Generated by Django 5.1.4 on 2026-07-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_verifier_in_training_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact of Client'),
        ),
    ]
