# Generated by Django 5.1.4 on 2026-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_company_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact of Client'),
        ),
    ]
