# Generated by Django 5.1.4 on 2026-07-15 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_formtablelayout_multiple_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtablelayout',
            options={'ordering': ['table_number', 'pk'], 'verbose_name': 'Form Table Layout', 'verbose_name_plural': 'Form Table Layouts'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_recipie_f3d353_idx',
            old_name='core_notif_recip_read_idx',
        ),
        migrations.AlterField(
            model_name='formtablelayout',
            name='cell_dropdowns',
            field=models.JSONField(blank=True, default=list, help_text='Column dropdown configs: {col, options, is_active}.'),
        ),
        migrations.AlterField(
            model_name='formtablelayout',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Table Description'),
        ),
        migrations.AlterField(
            model_name='formtablelayout',
            name='table_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Table Heading'),
        ),
        migrations.AlterField(
            model_name='formtablelayout',
            name='table_number',
            field=models.PositiveIntegerField(default=1, help_text='Internal order index; assigned automatically.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
