# Generated by Django 5.1.4 on 2026-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_formtablelayout_heading_description_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtablelayout',
            name='table_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Table Heading'),
        ),
        migrations.AlterField(
            model_name='formtablelayout',
            name='table_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name of Table'),
        ),
    ]
