# Generated by Django 5.1.4 on 2026-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_formtablelayout_table_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtablelayout',
            name='table_note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
