# Generated by Django 5.1.4 on 2026-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_formtablelayout_table_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtablelayout',
            name='cell_dropdowns',
            field=models.JSONField(blank=True, default=list, help_text='Dropdown configs: {col, rows, options, is_active}. Empty rows = all rows.'),
        ),
    ]
