# Generated by Django 5.1.4 on 2026-08-01 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_formtablelayout_multiple_summaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrecord',
            name='current_reviewer',
            field=models.ForeignKey(blank=True, help_text='User currently assigned to review this form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms_awaiting_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formrecord',
            name='last_submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who last submitted/forwarded this form for review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms_last_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formrecord',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='formreview',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
